#!/usr/bin/env python
import os
# ignore when django autoreloader restarts program
if os.environ.get('RUN_MAIN') != 'true':
    if not os.environ.get('DJANGO_SETTINGS_MODULE'):
        os.environ['DJANGO_SETTINGS_MODULE'] = 'occupywallst.settings'
from django.core.management import execute_from_command_line
from django.conf import settings
execute_from_command_line()
