#!/usr/bin/env python
import os
import sys
# ignore when django autoreloader restarts program
if os.environ.get('RUN_MAIN') != 'true':
    if os.environ.get('DJANGO_SETTINGS_MODULE'):
        print >>sys.stderr, ("Overriding DJANGO_SETTINGS_MODULE not permitted "
                             "in development mode.  Use occupywallst command "
                             "instead.")
        sys.exit(1)
    else:
        os.environ['DJANGO_SETTINGS_MODULE'] = 'occupywallst.settings_dev'
from django.core.management import execute_from_command_line
from django.conf import settings
execute_from_command_line()
